$path = "src\app\dashboard\invoices\new\page.tsx"
$lines = Get-Content $path

$startIdx = -1
for ($i = 0; $i -lt $lines.Count; $i++) {
    if ($lines[$i].Trim() -eq "const handleSubmit = async () => {") { $startIdx = $i; break }
}

$endIdx = -1
if ($startIdx -ge 0) {
    for ($i = $startIdx + 1; $i -lt $lines.Count; $i++) {
        if ($lines[$i].Trim() -eq "const waLink = () => {") { $endIdx = $i; break }
    }
}

if ($startIdx -lt 0 -or $endIdx -lt 0) {
    Write-Host "SAFETY CHECK FAILED: could not locate boundaries. startIdx=$startIdx endIdx=$endIdx. No changes made." -ForegroundColor Red
} else {
    Write-Host "Found function: replacing lines $($startIdx+1) through $($endIdx)"

    $newFunc = @(
        '  const handleSubmit = async () => {',
        '    if (!customerId) { setError("Please select a customer"); return }',
        '    if (items.length === 0) { setError("Add at least one item"); return }',
        '    if (hasStockErrors) {',
        '      setError("Cannot save: some items have insufficient stock. Please adjust quantities.");',
        '      return',
        '    }',
        '',
        '    setSaving(true); setError("")',
        '',
        '    if (editId) {',
        '      try {',
        '        let automationConfig = {}',
        '        let automationAllowed = false',
        '        if (automationFeatureEnabled) {',
        '          const { data: settings } = await supabase',
        '            .from("company_settings")',
        '            .select("invoice_automation_config")',
        '            .eq("company_id", companyId)',
        '            .maybeSingle()',
        '          automationConfig = settings?.invoice_automation_config || {}',
        '          automationAllowed = true',
        '        }',
        '        const payloadItems = items.map(i => ({',
        '          product_id: i.product_id || null,',
        '          description: i.description,',
        '          qty: i.qty,',
        '          unit_price: i.unit_price,',
        '          cost_price: i.cost_price || 0,',
        '          project_id: i.project_id || null,',
        '          donor_id: i.donor_id || null,',
        '          tax_code_id: taxEnabled ? (i.tax_code_id || null) : null,',
        '          tax_rate: taxEnabled ? (i.tax_rate || 0) : 0,',
        '          tax_amount: taxEnabled ? (i.tax_amount || 0) : 0,',
        '        }))',
        "        const { data, error: rpcError } = await supabase.rpc('update_invoice_transaction', {",
        '          p_invoice_id: Number(editId),',
        '          p_company_id: companyId,',
        '          p_party_id: customerId,',
        '          p_invoice_date: invoiceDate,',
        '          p_due_date: dueDate,',
        '          p_items: payloadItems,',
        "          p_reference: reference || '',",
        "          p_notes: notes || '',",
        "          p_user_email: selectedCustomer?.email || 'system',",
        '          p_tax_enabled: taxEnabled,',
        '          p_automation_config: automationConfig,',
        '          p_automation_allowed: automationAllowed,',
        '          p_business_type: businessType,',
        '        })',
        '        if (rpcError) {',
        '          setError(rpcError.message || "Failed to update invoice")',
        '          setSaving(false)',
        '          return',
        '        }',
        '        if (!data || !data.success) {',
        '          setError(data?.error || "Failed to update invoice")',
        '          setSaving(false)',
        '          return',
        '        }',
        '        setSavedInvoiceId(Number(editId))',
        '        setFlash("Invoice updated successfully.")',
        '        router.push(`/dashboard/invoices/${editId}`)',
        '      } catch (err: any) {',
        '        setError(err.message || "Network error")',
        '        setSaving(false)',
        '      }',
        '      return',
        '    }',
        '',
        '    try {',
        '      let automationConfig = {}',
        '      let automationAllowed = false',
        '      if (automationFeatureEnabled) {',
        '        const { data: settings } = await supabase',
        '          .from("company_settings")',
        '          .select("invoice_automation_config")',
        '          .eq("company_id", companyId)',
        '          .maybeSingle()',
        '        automationConfig = settings?.invoice_automation_config || {}',
        '        automationAllowed = true',
        '      }',
        '      const payloadItems = items.map(i => ({',
        '        product_id: i.product_id || null,',
        '        description: i.description,',
        '        qty: i.qty,',
        '        unit_price: i.unit_price,',
        '        cost_price: i.cost_price || 0,',
        '        project_id: i.project_id || null,',
        '        donor_id: i.donor_id || null,',
        '        tax_code_id: taxEnabled ? (i.tax_code_id || null) : null,',
        '        tax_rate: taxEnabled ? (i.tax_rate || 0) : 0,',
        '        tax_amount: taxEnabled ? (i.tax_amount || 0) : 0,',
        '      }))',
        "      const { data, error: rpcError } = await supabase.rpc('create_invoice_transaction', {",
        '        p_company_id: companyId,',
        '        p_party_id: customerId,',
        '        p_invoice_date: invoiceDate,',
        '        p_due_date: dueDate,',
        '        p_items: payloadItems,',
        "        p_reference: reference || '',",
        "        p_notes: notes || '',",
        "        p_user_email: selectedCustomer?.email || 'system',",
        '        p_tax_enabled: taxEnabled,',
        '        p_automation_config: automationConfig,',
        '        p_automation_allowed: automationAllowed,',
        '        p_business_type: businessType,',
        '      })',
        '      if (rpcError) {',
        '        setError(rpcError.message || "Failed to save invoice")',
        '        setSaving(false)',
        '        return',
        '      }',
        '      if (!data || !data.success) {',
        '        setError(data?.error || "Failed to save invoice")',
        '        setSaving(false)',
        '        return',
        '      }',
        '      const newInvoiceId = data.invoice_id',
        '      setSavedInvoiceId(newInvoiceId || null)',
        '      setFlash("Invoice saved successfully.")',
        '      setSaving(false)',
        '    } catch (err: any) {',
        '      setError(err.message || "Network error")',
        '      setSaving(false)',
        '    }',
        '  }',
        ''
    )

    $before = $lines[0..($startIdx - 1)]
    $after = $lines[$endIdx..($lines.Count - 1)]
    $result = $before + $newFunc + $after
    Set-Content -Path $path -Value $result
    Write-Host "SUCCESS: file rebuilt cleanly." -ForegroundColor Green
}