import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

const NAVY   = [7,8,91] as [number,number,number]
const MUTED  = [107,114,128] as [number,number,number]
const BORDER = [229,231,235] as [number,number,number]
const WHITE  = [255,255,255] as [number,number,number]
const ROW_ALT = [248,249,252] as [number,number,number]

const pkr = (n:number) => "PKR " + n.toLocaleString("en-PK",{minimumFractionDigits:2,maximumFractionDigits:2})

async function loadImage(url:string):Promise<string|null>{
  try {
    const r = await fetch(url)
    if(!r.ok) return null
    const b = await r.blob()
    return new Promise(res => {
      const reader = new FileReader()
      reader.onload = () => res(reader.result as string)
      reader.onerror = () => res("")
      reader.readAsDataURL(b)
    })
  } catch { return null }
}

export interface DepreciationEntryRow {
  date: string
  entryNo: string
  description: string
  account: string
  debit: number
  credit: number
}

export interface DepreciationEntryPDFData {
  companyName: string
  companyAddress?: string
  companyPhone?: string
  companyEmail?: string
  companyTagline: string
  logoUrl?: string | null
  fromDate: string
  toDate: string
  entries: DepreciationEntryRow[]
}

export async function generateDepreciationEntryPDF(data: DepreciationEntryPDFData): Promise<jsPDF> {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" })
  const PW = 297, PH = 210, ML = 14, MR = 14
  const LOGO_SIZE = 20, LOGO_X = ML, LOGO_Y = 7

  let logoData: string | null = null
  if (data.logoUrl) logoData = await loadImage(data.logoUrl)

  if (logoData) doc.addImage(logoData, "PNG", LOGO_X, LOGO_Y, LOGO_SIZE, LOGO_SIZE)
  const textX = logoData ? LOGO_X + LOGO_SIZE + 5 : ML

  doc.setTextColor(...NAVY).setFont("helvetica","bold").setFontSize(14).text(data.companyName || "", textX, LOGO_Y + 7)
  doc.setFont("helvetica","normal").setFontSize(8.5).setTextColor(...MUTED).text(data.companyTagline || "", textX, LOGO_Y + 13)

  let infoY = LOGO_Y + 19
  if (data.companyAddress) { doc.text(data.companyAddress, textX, infoY); infoY += 4 }
  if (data.companyPhone) { doc.text("Phone: " + data.companyPhone, textX, infoY); infoY += 4 }
  if (data.companyEmail) { doc.text("Email: " + data.companyEmail, textX, infoY) }

  doc.setFont("helvetica","bold").setFontSize(18).setTextColor(...NAVY).text("DEPRECIATION ENTRIES", PW - MR, LOGO_Y + 8, { align: "right" })
  doc.setFont("helvetica","normal").setFontSize(8.5).setTextColor(...MUTED).text(`From: ${data.fromDate}  To: ${data.toDate}`, PW - MR, LOGO_Y + 16, { align: "right" })

  const headerBottom = Math.max(LOGO_Y + LOGO_SIZE, infoY) + 6
  doc.setDrawColor(...NAVY).setLineWidth(0.6).line(ML, headerBottom, PW - MR, headerBottom)

  let Y = headerBottom + 6

  const headers = ["Date", "Entry #", "Description", "Account", "Debit", "Credit"]
  const rows = data.entries.map(e => [
    e.date,
    e.entryNo,
    e.description,
    e.account,
    e.debit > 0 ? pkr(e.debit) : "–",
    e.credit > 0 ? pkr(e.credit) : "–"
  ])

  const totalDebit = data.entries.reduce((s,e)=> s + e.debit, 0)
  const totalCredit = data.entries.reduce((s,e)=> s + e.credit, 0)
  rows.push(["", "", "", "Total", pkr(totalDebit), pkr(totalCredit)])

  autoTable(doc, {
    startY: Y, margin: { left: ML, right: MR },
    head: [headers],
    body: rows,
    styles: { fontSize: 7.5, cellPadding: { top: 2, bottom: 2, left: 2, right: 2 }, textColor: [17,24,39], lineColor: BORDER, lineWidth: 0.2 },
    headStyles: { fillColor: NAVY, textColor: WHITE, fontStyle: "bold", fontSize: 8 },
    alternateRowStyles: { fillColor: ROW_ALT },
    columnStyles: {
      0: { cellWidth: 28 },
      1: { cellWidth: 40 },
      2: { cellWidth: "auto" },
      3: { cellWidth: 50 },
      4: { cellWidth: 38, halign: "right" },
      5: { cellWidth: 38, halign: "right" },
    },
    didParseCell: (hookData) => {
      const rowData = hookData.row.raw as string[]
      if (rowData && rowData[3] === "Total") {
        hookData.cell.styles.fontStyle = "bold"
        hookData.cell.styles.fillColor = NAVY
        hookData.cell.styles.textColor = WHITE
      }
    },
    didDrawPage: () => {
      const str = "Page " + doc.getNumberOfPages()
      doc.setFont("helvetica","normal").setFontSize(7.5).setTextColor(...MUTED)
      doc.text(str, PW - MR, PH - 8, { align: "right" })
    }
  })

  doc.setDrawColor(...NAVY).setLineWidth(0.4).line(ML, PH - 14, PW - MR, PH - 14)
  doc.setFont("helvetica","normal").setFontSize(7.5).setTextColor(...MUTED).text(`Generated by ${data.companyName}  ·  ${data.companyTagline}`, PW/2, PH-8, { align: "center" })

  return doc
}