import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

const NAVY   = [7,8,91] as [number,number,number]
const DARK   = [17,24,39] as [number,number,number]
const MUTED  = [107,114,128] as [number,number,number]
const BORDER = [229,231,235] as [number,number,number]
const WHITE  = [255,255,255] as [number,number,number]
const ROW_ALT = [248,249,252] as [number,number,number]

async function loadImage(url:string):Promise<string|null>{ try{const r=await fetch(url);if(!r.ok)return null;const b=await r.blob();return new Promise(res=>{const reader=new FileReader();reader.onload=()=>res(reader.result as string);reader.onerror=()=>res("");reader.readAsDataURL(b)})}catch{return null} }

export interface ProductLedgerLine{ date:string; type:string; invoice_no:string; qty_in:number; qty_out:number; balance:number; isOpening?:boolean }
export interface ProductLedgerPDFData{ companyName:string; companyAddress?:string; companyPhone?:string; companyEmail?:string; companyTagline:string; logoUrl?:string|null; productName:string; productCode:string; startDate:string; endDate:string; totalInflow:number; totalOutflow:number; closingBalance:number; ledgerLines:ProductLedgerLine[] }

export async function generateProductLedgerPDF(data:ProductLedgerPDFData):Promise<jsPDF>{
  const doc = new jsPDF({orientation:"landscape",unit:"mm",format:"a4"})
  const PW=297,PH=210,ML=14,MR=14
  const LOGO_SIZE=20,LOGO_X=ML,LOGO_Y=7
  let logoData:string|null=null
  if(data.logoUrl) logoData=await loadImage(data.logoUrl)
  if(logoData) doc.addImage(logoData,"PNG",LOGO_X,LOGO_Y,LOGO_SIZE,LOGO_SIZE)
  const textX=logoData?LOGO_X+LOGO_SIZE+5:ML
  doc.setTextColor(...NAVY).setFont("helvetica","bold").setFontSize(14).text(data.companyName||"",textX,LOGO_Y+7)
  doc.setFont("helvetica","normal").setFontSize(8.5).setTextColor(...MUTED).text(data.companyTagline||"",textX,LOGO_Y+13)
  let infoY=LOGO_Y+19
  if(data.companyAddress){doc.text(data.companyAddress,textX,infoY);infoY+=4}
  if(data.companyPhone){doc.text("Phone: "+data.companyPhone,textX,infoY);infoY+=4}
  if(data.companyEmail){doc.text("Email: "+data.companyEmail,textX,infoY)}
  doc.setFont("helvetica","bold").setFontSize(24).setTextColor(...NAVY).text("PRODUCT LEDGER",PW-MR,LOGO_Y+8,{align:"right"})
  doc.setFont("helvetica","normal").setFontSize(8.5).setTextColor(...MUTED).text(`${data.productCode} – ${data.productName}`,PW-MR,LOGO_Y+16,{align:"right"})
  doc.text(`From: ${data.startDate}  To: ${data.endDate}`,PW-MR,LOGO_Y+21,{align:"right"})
  const HEADER_BOTTOM=LOGO_Y+LOGO_SIZE+5
  doc.setDrawColor(...NAVY).setLineWidth(0.6).line(ML,HEADER_BOTTOM,PW-MR,HEADER_BOTTOM)
  let Y=HEADER_BOTTOM+6
  const headers=["Date","Type","Invoice #","Inflow","Outflow","Balance"]
  const rows:any[]=data.ledgerLines.map(l=>[
    l.isOpening?"":l.date,
    l.type==="Opening"?"Opening":l.type==="purchase"?"Purchase":"Sale",
    l.invoice_no||"",
    l.qty_in>0?l.qty_in.toString():"–",
    l.qty_out>0?l.qty_out.toString():"–",
    l.balance.toString()
  ])
  rows.push(["","","Total",data.totalInflow.toString(),data.totalOutflow.toString(),data.closingBalance.toString()])
  autoTable(doc,{
    startY:Y,margin:{left:ML,right:MR},head:[headers],body:rows,
    styles:{fontSize:7.5,cellPadding:{top:2,bottom:2,left:2,right:2},textColor:DARK,lineColor:BORDER,lineWidth:0.2},
    headStyles:{fillColor:NAVY,textColor:WHITE,fontStyle:"bold",fontSize:8},
    alternateRowStyles:{fillColor:ROW_ALT},
    columnStyles:{0:{cellWidth:28},1:{cellWidth:26},2:{cellWidth:"auto"},3:{cellWidth:28,halign:"right"},4:{cellWidth:28,halign:"right"},5:{cellWidth:32,halign:"right"}},
    didParseCell:(hookData)=>{
      const rowData=hookData.row.raw as string[]
      if(rowData[2]==="Opening"||rowData[1]==="Opening"){hookData.cell.styles.fontStyle="bold";hookData.cell.styles.fillColor=[240,240,245]}
      if(rowData[2]==="Total"){hookData.cell.styles.fontStyle="bold";hookData.cell.styles.fillColor=NAVY;hookData.cell.styles.textColor=WHITE}
    }
  })
  doc.setDrawColor(...NAVY).setLineWidth(0.4).line(ML,PH-14,PW-MR,PH-14)
  doc.setFont("helvetica","normal").setFontSize(7.5).setTextColor(...MUTED).text(`Generated by ${data.companyName}  ·  ${data.companyTagline}`,PW/2,PH-8,{align:"center"})
  return doc
}